In [112]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

numpy merupakan library yang digunakan untuk komputasi matriks.
matplotlib merupakan library python untuk presentasi data berupa grafik atau plot. 

In [113]:
dataset = pd.read_csv('Data (2).csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [114]:
print(x)

[['Indonesia' 44.0 72000.0]
 ['Thailand' nan 48000.0]
 ['Myanmar' 30.0 54000.0]
 ['Malaysia' 38.0 nan]
 ['Singapore' 40.0 73000.0]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['Germany' 48.0 79000.0]
 ['Spain' 50.0 83000.0]
 ['Germany' 37.0 67000.0]
 ['France' 38.0 58000.0]
 ['Spain' 40.0 52000.0]
 ['France' 45.0 79000.0]
 ['Germany' 34.0 nan]
 ['France' 43.0 48000.0]]


In [115]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes']


In [116]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:,1:3])

In [117]:
print(x)

[['Indonesia' 44.0 72000.0]
 ['Thailand' 40.15384615384615 48000.0]
 ['Myanmar' 30.0 54000.0]
 ['Malaysia' 38.0 63307.692307692305]
 ['Singapore' 40.0 73000.0]
 ['France' 35.0 58000.0]
 ['Spain' 40.15384615384615 52000.0]
 ['Germany' 48.0 79000.0]
 ['Spain' 50.0 83000.0]
 ['Germany' 37.0 67000.0]
 ['France' 38.0 58000.0]
 ['Spain' 40.0 52000.0]
 ['France' 45.0 79000.0]
 ['Germany' 34.0 63307.692307692305]
 ['France' 43.0 48000.0]]


In [118]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [119]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 40.15384615384615 48000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 38.0 63307.692307692305]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 40.0 73000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.15384615384615 52000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 38.0 58000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.0 52000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 45.0 79000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 34.0 63307.692307692305]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 43.0 48000.0]]


In [120]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [121]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 1 1 0 1]


In [122]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x,y, test_size=0.2, random_state=1)

In [123]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 38.0 58000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 40.0 73000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 40.15384615384615 48000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 34.0 63307.692307692305]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 43.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 45.0 79000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.0 52000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 58000.0]]


In [124]:
print(x_test)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 38.0 63307.692307692305]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.15384615384615 52000.0]]


In [125]:
print(y_train)

[0 1 1 1 0 0 1 1 0 1 1 1]


In [126]:
print(y_test)

[0 1 0]


In [129]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [130]:
print(x_train)

[[0.0 0.0 0.0 0.0 3.3166247903554007 -0.3015113445777637
  -0.4472135954999579 -0.30151134457776363 -1.866303679985252
  -0.785538350554371]
 [1.0 0.0 0.0 0.0 -0.3015113445777637 -0.3015113445777637
  -0.4472135954999579 -0.30151134457776363 -0.32382222791797133
  -0.4341577550375769]
 [0.0 0.0 0.0 0.0 -0.3015113445777637 3.3166247903554007
  -0.4472135954999579 -0.30151134457776363 0.06179813509884882
  0.8835194781504009]
 [0.0 0.0 0.0 0.0 -0.3015113445777637 -0.3015113445777637
  -0.4472135954999579 3.3166247903554 0.09146123994629643
  -1.3126092438295622]
 [0.0 1.0 0.0 0.0 -0.3015113445777637 -0.3015113445777637
  -0.4472135954999579 -0.30151134457776363 -1.0950629539516117
  0.03209726593663038]
 [0.0 0.0 1.0 0.0 -0.3015113445777637 -0.3015113445777637
  -0.4472135954999579 -0.30151134457776363 0.8330388611324892
  0.7956743292712024]
 [1.0 0.0 0.0 0.0 -0.3015113445777637 -0.3015113445777637
  -0.4472135954999579 -0.30151134457776363 0.640228679624079
  -1.3126092438295622]
 [0.0

In [131]:
print(x_test)

[[0.0 0.0 0.0 1.0 -0.3015113445777637 -0.3015113445777637
  -0.4472135954999579 -0.30151134457776363 -0.32382222791797133
  0.03209726593663038]
 [0.0 1.0 0.0 0.0 -0.3015113445777637 -0.3015113445777637
  -0.4472135954999579 -0.30151134457776363 1.6042795871661295
  1.410590371425592]
 [0.0 0.0 0.0 0.0 -0.3015113445777637 -0.3015113445777637
  2.23606797749979 -0.30151134457776363 0.09146123994629643
  -0.961228648312768]]
